name: "CI: Semgrep Cloud Scan (No SARIF Upload)"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  semgrep-scan:
    name: "Run Semgrep Cloud + Generate SARIF (No Upload)"
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Install Semgrep CLI
      - name: Install Semgrep CLI
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      # 4) Run Semgrep in “Cloud” mode (this can exit code 2 if it finds issues)
      - name: Run Semgrep Cloud Scan
        run: |
          semgrep ci --config=p/ci --token ${{ secrets.SEMGREP_TOKEN }}

      # 5) Generate SARIF via “semgrep scan” (CE) so we get a local file
      - name: Generate SARIF Report (debug)
        if: always()
        run: |
          echo "=== Listing BEFORE semgrep scan ==="
          ls -la
          # The trailing “.” is critical; it tells Semgrep to scan the current directory.
          semgrep scan --config=p/ci --output semgrep-results.sarif --output-format sarif .
          echo "=== Listing AFTER semgrep scan ==="
          ls -la