name: "CI: Semgrep Cloud Scan (Fix SARIF Flags)"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  semgrep-scan:
    name: "Run Semgrep Cloud + Generate SARIF"
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Install Semgrep CLI
      - name: Install Semgrep CLI
        run: |
          python -m pip install --upgrade pip
          pip install semgrep

      # 4) Confirm that SEMGREP_AUTH_TOKEN is present
      - name: Confirm Semgrep Auth Token
        run: |
          if [ -z "$SEMGREP_AUTH_TOKEN" ]; then
            echo "ERROR: SEMGREP_AUTH_TOKEN is not set"
            exit 1
          fi
          echo "Semgrep auth token is set."
        env:
          SEMGREP_AUTH_TOKEN: ${{ secrets.SEMGREP_AUTH_TOKEN }}

      # 5) Run Semgrep in “Cloud” mode (using the env var for auth)
      - name: Run Semgrep Cloud Scan (continue on findings)
        run: |
          semgrep ci --config=p/ci --strict=false
        env:
          SEMGREP_AUTH_TOKEN: ${{ secrets.SEMGREP_AUTH_TOKEN }}

      - name: Generate SARIF Report (debug)
        if: always()
        run: |
          semgrep scan --config=p/ci --sarif -o semgrep-results.sarif .
          ls -la
